/* internal function keydefaults */

KEYS std_keytab[] = {
    "\033[C", 	  C_RT,    "(Right)",        "Right file on screen",
    "\06",       _C_RT,    "",               "Right file on screen",
    "\033[D",	  C_LF,    "(Left)",         "Left file on screen",
    "\02",       _C_LF,    "",               "Left file on screen",
    "\033[A",     C_UP,    "(Up)",           "One file up on screen",
    "\020",      _C_UP,    "",               "One file up on screen",
    "\033[B",	  C_DN,    "(Down)",         "One file down on screen",
    "\016",      _C_DN,    "",               "One file down on screen",
    "\033[Ow",	  C_END,   "(End)",          "Jump to the end of directory",
    "\05",       _C_END,   "",               "Jump to the end of directory",
    "\033[H",	  C_HOME,  "(Home)",         "Jump to the begin of directory",
    "\01",       _C_HOME,  "",               "Jump to the begin of directory",
    "\033[5~",	  C_PGUP,  "(PgUp)",         "One page up in directory",
    "\025",      _C_PGUP,  "",               "One page up in directory",
    "\033[6~",	  C_PGDN,  "(PgDn)",         "One page down in directory",
    "\026",      _C_PGDN,  "",               "One page down in directory",
    "q",	  QX_QUIT, "",               "Quit qx",
    " ",	  QX_TAG,  "(Space)",        "Tags file",
    "?",	  QX_HELP, "",               "This help screen",
    "T",          QX_MATCH,"",               "Tag all matching files",
    "\011",       QX_CHDIR,"(Tab)",          "Change directory",
    "\014",	  QX_REFRESH,"",             "Refreshs screen",
    "*",	  QX_TAGALL,"",              "Tag all files in the directory",
    ">",          QX_INC,"",                 "Go to next procedure item",
    "<",          QX_DEC,"",                 "Go to previous procedure item",
    "0",          QX_LO,"",                  "Select default layout",
    "1",          QX_LO1,"",                 "Choose layout one",
    "2",          QX_LO2,"",                 "Choose layout two",
    "3",          QX_LO3,"",                 "Choose layout three",
    "4",          QX_LO4,"",                 "Choose layout four",
    "5",          QX_LO5,"",                 "Choose layout five",
    "6",          QX_LO6,"",                 "Choose layout six",
    "7",          QX_LO7,"",                 "Choose layout seven",
    "8",          QX_LO8,"",                 "Choose layout eight",
    "9",          QX_LO9,"",                 "Choose layout nine",
    "_",          QX_UNTAGALL,"",            "Untag all files in directory",
    "G",          QX_GOTO_DIR,"",            "Change to given directory",
    "D",          QX_UPDATE_DIR,"",          "Update the whole directory",
    "\032",       QX_SHELL,"",               "Shell escape",
    "~",          QX_GOTO_HOME,"",           "Jump to the home directory",
    "\012",       QX_START_PROC,"(Enter)",   "Start selected proc",
    "\033[[A",    QX_SELECT,"(F1)",          "Jump to default directory",
    "\033[[B",    QX_SELECT1,"(F2)",         "Jump to directory one",
    "\033[[C",    QX_SELECT2,"(F3)",         "Jump to directory two",
    "\033[[D",    QX_SELECT3,"(F4)",         "Jump to directory three",
    "\033[[E",    QX_SELECT4,"(F5)",         "Jump to directory four",
    "\033[17~",   QX_SELECT5,"(F6)",         "Jump to directory five",
    "\033[18~",   QX_SELECT6,"(F7)",         "Jump to directory six",
    "\033[19~",   QX_SELECT7,"(F8)",         "Jump to directory seven",
    "\033[20~",   QX_SELECT8,"(F9)",         "Jump to directory eight",
    "\033[21~",   QX_SELECT9,"(F10)",        "Jump to directory nine",
    "\033[23~",   QX_SELECT10,"(F11)",       "Jump to directory ten",
    "\033[24~",   QX_SELECT11,"(F12)",       "Jump to directory eleven",
    "\022",       QX_RENAME,"",              "Rename file",
    "F",          QX_FULLNAME,"",            "Display whole filename on screen",
    "\177",       QX_SHOWDIRTABLE,"(BS)",    "Display directory table",
    "i",	  QX_TAG_INVERSE,  "",       "Untags all tagged files and vise versa",
    ".",          QX_NOHIDDEN, "",           "Hide files beginning with a dot",
    ""            ,0};

char *std_prefix[] = {"\033","\030"};
